[PHP]
allow_url_include = 0
date.timezone = UTC
display_errors = 0
error_log = /dev/stderr
error_reporting = E_ALL & ~E_STRICT & ~E_DEPRECATED & ~E_USER_DEPRECATED
expose_php = 0
mail.log = /dev/stdout
memory_limit = 256M
opcache.enable = 1
opcache.error_log = /dev/stderr
opcache.jit_debug = 0
opcache.max_accelerated_files = 130987
opcache.preload_user = www-data
post_max_size = 100M
report_zend_debug = 0
request_order = GP
sendmail_path = /usr/local/utils/sendmail -t
session.cookie_httponly = 1
session.cookie_lifetime = 0
session.cookie_samesite = Lax
session.cookie_secure = 0
session.use_cookies = 1
syslog.facility = syslog
upload_max_filesize = 100M
variables_order = EGPCS
extension=mongodb.so
